version: "0.2"
# Suggestions can sometimes take longer on CI machines,
# leading to inconsistent results.
suggestionsTimeout: 5000 # ms

words:
  - bigsmiles
  - Cheminformatics
  - silico
  - microphase
  - diblock
  - nanostructures
  - Diblock
  - nanoscale
  - SLSP
  - Wodw
  - Skokie
  - Riebold
  - ludwigschneider
  - AMSO
  - Ptens
  - SSAGES
  - CUDA
  - webfactory
  - SKBUILD
  - pybind
  - cpmaddpackage
  - memarray
  - pyproject
  - ctypes
  - nanobind
  - scikit
  - numpy
  - setuptools
  - pxezdgr
  - pathspec
  - tmpnbo
  - libamso
  - cpython
  - platlib
  - ephem
  - filt
  - nvcc
  - cout
  - endl
  - demangled
  - isystem
  - NVCC
  - lcudart
  - Nsight
  - CCCL
  - pytest
  - allclose
  - thrust
  - DLCUDA
  - dltensor
  - DLPACK
  - deleter
  - nullptr
  - constexpr
  - DLCPU
  - strided
  - RAII
  - ndarray
  - dtype
  - ndim
  - Pimpl
  - cupy
  - CUPY
  - NUMBA
  - ndim
  - NDIM
  - Malloc
  - noexcept
  - Sutter
  - dtype
  - strcmp
  - forcecast
