version: "0.2"
# Suggestions can sometimes take longer on CI machines,
# leading to inconsistent results.
suggestionsTimeout: 5000 # ms

words:
  - bigsmiles
  - Cheminformatics
  - silico
  - microphase
  - diblock
  - nanostructures
  - Diblock
  - nanoscale
  - SLSP
  - Wodw
  - Skokie
  - Riebold
  - ludwigschneider
  - AMSO
  - Ptens
  - SSAGES
  - CUDA
  - webfactory
  - SKBUILD
  - pybind
  - cpmaddpackage
  - memarray
  - pyproject
  - ctypes
  - nanobind
